DELIMITER //
CREATE TRIGGER USER_INSERT_PROTAGONIST
AFTER INSERT ON PROTAGONIST
FOR EACH ROW
BEGIN
    INSERT INTO MOVIE_TRIGGER.AFTER_INSERT_PROTAGONIST (aip_user, aip_pro_vname, aip_pro_nname)
    VALUES (USER(), NEW.pro_fname, NEW.pro_sname);
END;
//

CREATE TRIGGER USER_UPDATE_COUNTRY
AFTER UPDATE ON COUNTRY
FOR EACH ROW
BEGIN
    INSERT INTO MOVIE_TRIGGER.AFTER_UPDATE_COUNTRY (auc_user, auc_cou_id, auc_cou_old_name, auc_cou_new_name)
    VALUES (USER(), NEW.cou_id, OLD.cou_name, NEW.cou_name);
END;
//
DELIMITER ;

